version: "3.1"
services:
  quantumdatabase:
    container_name: quantumtooldatabase
    image: mariadb:10.6.14
    volumes:
      - ${QUANTUM_DATABASE_LOCATION}:/var/lib/mysql
    restart: always
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysql", "pingadmin", "--user=root", '--password="${QUANTUM_ROOT_PASSWORD}"']
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - MYSQL_ROOT_PASSWORD=${QUANTUM_ROOT_PASSWORD}
      - MYSQL_DATABASE=${QUANTUM_DATABASE}
  quantumtoolwebapp:
      container_name: quantumtoolwebapp
      image: quantum_online_tool
      environment:
        - QUANTUM_DATABASE=${QUANTUM_DATABASE}
        - QUANTUM_ROOT_PASSWORD=${QUANTUM_ROOT_PASSWORD}
        - QUANTUM_DATABASE_HOST=quantumdatabase
        - QUANTUM_DATABASE_PORT=3306
        - DJANGO_DEBUG=0
        - DJANGO_WEB_URL=${DJANGO_WEB_URL}
      ports:
        - 8000:8000
      depends_on:
        - quantumdatabase